[phases.setup]
nixPkgs = [
  "python311", 
  "python311Packages.pip",   # Ensure pip is installed
  "gcc"
]

[phases.install]
cmds = [
  "python -m pip install --upgrade pip",  # Upgrade pip if needed
  "python -m pip install -r requirements.txt"
]

[start]
cmd = "gunicorn nfms-aqvh.wsgi:application --bind 0.0.0.0:$PORT"
