[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = [
  "python -m ensurepip --upgrade",  # Ensure pip is installed
  "python -m pip install -r requirements.txt"
]

[start]
cmd = "gunicorn nfms-aqvh.wsgi:application --bind 0.0.0.0:$PORT"
