# Generated by Django 4.2 on 2025-04-08 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_total_price_order_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='amount',
            new_name='total_price',
        ),
    ]
