# Generated by Django 4.2 on 2025-04-08 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_amount_order_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='created_at',
            new_name='create_account',
        ),
    ]
